spring.application.name=Proyecto_Eventos_Venta_Boletos

#Limites de subida de imagenes para los banners de los evento
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
